#remote_theme: just-the-docs/just-the-docs
#theme: jekyll-theme-dinky
#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/merlot@v0.2.0
#remote_theme: selwynpolit/merlot@v0.2.0
remote_theme: selwynpolit/merlotsp@v0.2.3


